# Generated by Django 5.2.4 on 2025-07-29 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_userskill_archived_userskill_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="session",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="session",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="flashcard",
            options={},
        ),
        migrations.RenameField(
            model_name="flashcard",
            old_name="answer",
            new_name="back_text",
        ),
        migrations.RenameField(
            model_name="flashcard",
            old_name="question",
            new_name="front_text",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="is_revision",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="archived_at",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="aux_flashcard_xp",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="aux_quiz_xp",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="completion_xp_awarded",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="core_lesson_xp",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="current_level",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="last_revision_pair_awarded_on",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="target_level",
        ),
        migrations.AddField(
            model_name="flashcard",
            name="created_on",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="user_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userauth.userskill",
            ),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=255)),
                ("option_1", models.CharField(max_length=255)),
                ("option_2", models.CharField(max_length=255)),
                ("option_3", models.CharField(max_length=255)),
                ("option_4", models.CharField(max_length=255)),
                ("created_on", models.DateField()),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userauth.userskill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_amount", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="userauth.skill"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LearningSession",
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
    ]
