# Generated by Django 5.2.4 on 2025-07-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userauth",
            "0003_remove_flashcard_session_remove_quizquestion_session_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("flashcards_json", models.JSONField(blank=True, default=list)),
                ("quiz_json", models.JSONField(blank=True, default=list)),
                ("completed", models.BooleanField(default=False)),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_sessions",
                        to="userauth.userskill",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_skill", "date")},
            },
        ),
    ]
