# Generated by Django 5.2.4 on 2025-07-29 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0004_learningsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="created_on",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
