# Generated by Django 5.2.4 on 2025-07-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0005_alter_quiz_created_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("teach", "Teach"), ("test", "Test")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("question", models.TextField(blank=True, null=True)),
                ("option_1", models.TextField(blank=True, null=True)),
                ("option_2", models.TextField(blank=True, null=True)),
                ("option_3", models.TextField(blank=True, null=True)),
                ("option_4", models.TextField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userauth.userskill",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
