# Generated by Django 5.2.4 on 2025-08-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0006_lessonitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="user_skill",
        ),
        migrations.AlterUniqueTogether(
            name="learningsession",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="learningsession",
            name="user_skill",
        ),
        migrations.RemoveField(
            model_name="lessonitem",
            name="user_skill",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="user_skill",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="user",
        ),
        migrations.RemoveField(
            model_name="xplog",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="xplog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="active_skills_count",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="weekly_progress_pct",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="Flashcard",
        ),
        migrations.DeleteModel(
            name="LearningSession",
        ),
        migrations.DeleteModel(
            name="LessonItem",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="QuizAttempt",
        ),
        migrations.DeleteModel(
            name="XPLog",
        ),
    ]
