# Generated by Django 5.2.4 on 2025-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0007_remove_flashcard_user_skill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="total_minutes_spent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
