# Generated by Django 5.2.4 on 2025-08-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0008_userskill_total_minutes_spent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="flashcards_cache",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userskill",
            name="lessons_cache",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userskill",
            name="quizzes_cache",
            field=models.TextField(blank=True, null=True),
        ),
    ]
